services:
  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    environment:
      - GITEA_INSTANCE_URL=https://git.sirblob.co
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=${GITEA_RUNNER_NAME:-MochaNet-Runner}
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
